import { Course } from '../types/course.types';

// Free Coursera Courses
export const freeCourses: Course[] = [
    {
        id: 'free-1',
        title: 'AI For Everyone',
        slug: 'ai-for-everyone',
        description: 'AI is not just for engineers. If you want to learn how AI can impact your work and your business.',
        provider: 'DeepLearning.AI',
        courseType: 'Course',
        averageRating: 4.8,
        reviewCount: 180000,
        price: 0,
        isFree: true,
        level: 'All Levels',
        enrollmentCount: 3200000,
        courseraUrl: 'https://www.coursera.org/learn/ai-for-everyone',
        skills: ['Machine Learning', 'Deep Learning', 'AI Strategy'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400&h=250&fit=crop'
    },
    {
        id: 'free-2',
        title: 'Introduction to Psychology',
        slug: 'introduction-to-psychology',
        description: 'This course will highlight the most interesting experiments within the field of psychology.',
        provider: 'University of Toronto',
        courseType: 'Course',
        averageRating: 4.7,
        reviewCount: 45000,
        price: 0,
        isFree: true,
        level: 'Beginner',
        enrollmentCount: 890000,
        courseraUrl: 'https://www.coursera.org/learn/introduction-psychology',
        skills: ['Psychology', 'Communication', 'Research Methods'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=250&fit=crop'
    },
    {
        id: 'free-3',
        title: 'The Science of Success',
        slug: 'science-of-success',
        description: 'Learn the science behind what drives success and how to apply it in your life.',
        provider: 'Wesleyan University',
        courseType: 'Course',
        averageRating: 4.6,
        reviewCount: 28000,
        price: 0,
        isFree: true,
        level: 'All Levels',
        enrollmentCount: 520000,
        courseraUrl: 'https://www.coursera.org/learn/the-science-of-success',
        skills: ['Success Strategies', 'Personal Development', 'Goal Setting'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&h=250&fit=crop'
    },
    {
        id: 'free-4',
        title: 'Introduction to Philosophy',
        slug: 'introduction-to-philosophy',
        description: 'Explore fundamental questions about the nature of reality, knowledge, and ethics.',
        provider: 'University of Edinburgh',
        courseType: 'Course',
        averageRating: 4.5,
        reviewCount: 32000,
        price: 0,
        isFree: true,
        level: 'Beginner',
        enrollmentCount: 680000,
        courseraUrl: 'https://www.coursera.org/learn/introduction-philosophy',
        skills: ['Philosophy', 'Critical Thinking', 'Logic'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=400&h=250&fit=crop'
    },
    {
        id: 'free-5',
        title: 'Financial Markets',
        slug: 'financial-markets',
        description: 'Learn about the financial markets, securities, and corporate finance from Yale.',
        provider: 'Yale University',
        courseType: 'Course',
        averageRating: 4.8,
        reviewCount: 55000,
        price: 0,
        isFree: true,
        level: 'Beginner',
        enrollmentCount: 1100000,
        courseraUrl: 'https://www.coursera.org/learn/financial-markets',
        skills: ['Finance', 'Investment', 'Risk Management'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400&h=250&fit=crop'
    },
    {
        id: 'free-6',
        title: 'Learning How to Learn',
        slug: 'learning-how-to-learn',
        description: 'A powerful mental tools to master any subject or skill, based on neuroscience.',
        provider: 'Arizona State University',
        courseType: 'Course',
        averageRating: 4.8,
        reviewCount: 210000,
        price: 0,
        isFree: true,
        level: 'All Levels',
        enrollmentCount: 4200000,
        courseraUrl: 'https://www.coursera.org/learn/learning-how-to-learn',
        skills: ['Learning Strategies', 'Memory', 'Study Techniques'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=400&h=250&fit=crop'
    },
    {
        id: 'free-7',
        title: 'Computer Science: Programming with a Purpose',
        slug: 'programming-with-a-purpose',
        description: 'Introduction to computer science and programming for those with no prior experience.',
        provider: 'Princeton University',
        courseType: 'Course',
        averageRating: 4.7,
        reviewCount: 18000,
        price: 0,
        isFree: true,
        level: 'Beginner',
        enrollmentCount: 340000,
        courseraUrl: 'https://www.coursera.org/learn/cs-programming',
        skills: ['Java', 'Programming', 'Computer Science Fundamentals'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=400&h=250&fit=crop'
    },
    {
        id: 'free-8',
        title: 'Introduction to Data Science',
        slug: 'intro-data-science',
        description: 'Get an overview of data science tools and methods including machine learning.',
        provider: 'IBM',
        courseType: 'Course',
        averageRating: 4.6,
        reviewCount: 42000,
        price: 0,
        isFree: true,
        level: 'Beginner',
        enrollmentCount: 780000,
        courseraUrl: 'https://www.coursera.org/learn/introduction-to-data-science',
        skills: ['Data Science', 'Python', 'Data Analysis'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=250&fit=crop'
    }
];

// Free Certifications from various providers
export const freeCertifications: Course[] = [
    {
        id: 'fc-1',
        title: 'Google IT Support Professional Certificate',
        slug: 'google-it-support',
        description: 'Learn from Google employees about the foundations of IT support to prepare for a career.',
        provider: 'Google',
        courseType: 'Professional Certificate',
        averageRating: 4.8,
        reviewCount: 75000,
        price: 0,
        isFree: true,
        level: 'Beginner',
        enrollmentCount: 1800000,
        courseraUrl: 'https://www.coursera.org/professional-certificates/google-it-support',
        skills: ['IT Support', 'Networking', 'Security', 'Systems Administration'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&h=250&fit=crop'
    },
    {
        id: 'fc-2',
        title: 'AWS Cloud Practitioner',
        slug: 'aws-cloud-practitioner',
        description: 'Fundamental understanding of AWS cloud concepts, services, security, and pricing.',
        provider: 'Amazon Web Services',
        courseType: 'Certification',
        averageRating: 4.7,
        reviewCount: 25000,
        price: 0,
        isFree: true,
        level: 'Beginner',
        enrollmentCount: 500000,
        courseraUrl: 'https://aws.amazon.com/certification/certified-cloud-practitioner/',
        skills: ['AWS', 'Cloud Computing', 'Cloud Architecture'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=250&fit=crop'
    },
    {
        id: 'fc-3',
        title: 'Google Cloud Digital Leader',
        slug: 'gcp-digital-leader',
        description: 'Demonstrate foundational knowledge of cloud computing and Google Cloud products.',
        provider: 'Google Cloud',
        courseType: 'Certification',
        averageRating: 4.6,
        reviewCount: 12000,
        price: 0,
        isFree: true,
        level: 'Beginner',
        enrollmentCount: 280000,
        courseraUrl: 'https://cloud.google.com/certification/cloud-digital-leader',
        skills: ['Google Cloud', 'Cloud Computing', 'Digital Transformation'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1573164713988-8665fc963095?w=400&h=250&fit=crop'
    },
    {
        id: 'fc-4',
        title: 'Microsoft Azure Fundamentals',
        slug: 'azure-fundamentals',
        description: 'Learn cloud computing concepts, core Azure services, security, and pricing.',
        provider: 'Microsoft',
        courseType: 'Certification',
        averageRating: 4.7,
        reviewCount: 18000,
        price: 0,
        isFree: true,
        level: 'Beginner',
        enrollmentCount: 420000,
        courseraUrl: 'https://learn.microsoft.com/en-us/certifications/azure-fundamentals/',
        skills: ['Microsoft Azure', 'Cloud Computing', 'Virtual Machines'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1633412802994-5c058f151b66?w=400&h=250&fit=crop'
    }
];

// Paid Professional Certificates
export const paidCourses: Course[] = [
    {
        id: 'paid-1',
        title: 'Google Data Analytics Professional Certificate',
        slug: 'google-data-analytics',
        description: 'Your path to a career in data analytics. Learn in-demand skills job-ready in less than 6 months.',
        provider: 'Google',
        courseType: 'Professional Certificate',
        averageRating: 4.8,
        reviewCount: 105000,
        price: 3237,
        isFree: false,
        level: 'Beginner',
        enrollmentCount: 2500000,
        courseraUrl: 'https://www.coursera.org/professional-certificates/google-data-analytics',
        skills: ['Data Analytics', 'SQL', 'R', 'Data Visualization', 'Tableau'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=250&fit=crop'
    },
    {
        id: 'paid-2',
        title: 'IBM Data Science Professional Certificate',
        slug: 'ibm-data-science',
        description: 'Launch your career in data science. Build job-ready skills in Python, SQL, machine learning.',
        provider: 'IBM',
        courseType: 'Professional Certificate',
        averageRating: 4.6,
        reviewCount: 85000,
        price: 4067,
        isFree: false,
        level: 'Beginner',
        enrollmentCount: 1800000,
        courseraUrl: 'https://www.coursera.org/professional-certificates/ibm-data-science',
        skills: ['Python', 'SQL', 'Machine Learning', 'Data Visualization', 'Statistics'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=400&h=250&fit=crop'
    },
    {
        id: 'paid-3',
        title: 'Meta Data Analyst Professional Certificate',
        slug: 'meta-data-analyst',
        description: 'Learn core data analysis skills including SQL, Python, and statistics.',
        provider: 'Meta',
        courseType: 'Professional Certificate',
        averageRating: 4.7,
        reviewCount: 12000,
        price: 4067,
        isFree: false,
        level: 'Beginner',
        enrollmentCount: 450000,
        courseraUrl: 'https://www.coursera.org/professional-certificates/meta-data-analyst',
        skills: ['SQL', 'Python', 'Data Analysis', 'Statistics', 'Tableau'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1543286386-713dfddb6cc2?w=400&h=250&fit=crop'
    },
    {
        id: 'paid-4',
        title: 'Google Project Management Professional Certificate',
        slug: 'google-project-management',
        description: 'Your path to a career in project management. Learn in-demand skills to become job-ready.',
        provider: 'Google',
        courseType: 'Professional Certificate',
        averageRating: 4.8,
        reviewCount: 95000,
        price: 3237,
        isFree: false,
        level: 'Beginner',
        enrollmentCount: 2100000,
        courseraUrl: 'https://www.coursera.org/professional-certificates/google-project-management',
        skills: ['Project Management', 'Agile', 'Scrum', 'Leadership', 'Risk Management'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&h=250&fit=crop'
    },
    {
        id: 'paid-5',
        title: 'Google UX Design Professional Certificate',
        slug: 'google-ux-design',
        description: 'Your path to a career in UX design. Learn to create user-friendly interfaces.',
        provider: 'Google',
        courseType: 'Professional Certificate',
        averageRating: 4.8,
        reviewCount: 52000,
        price: 3237,
        isFree: false,
        level: 'Beginner',
        enrollmentCount: 1500000,
        courseraUrl: 'https://www.coursera.org/professional-certificates/google-ux-design',
        skills: ['UX Design', 'Figma', 'User Research', 'Wireframing', 'Prototyping'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=250&fit=crop'
    },
    {
        id: 'paid-6',
        title: 'IBM Cybersecurity Analyst Professional Certificate',
        slug: 'ibm-cybersecurity',
        description: 'Launch your career in cybersecurity. Learn to identify, prevent, and respond to cyber threats.',
        provider: 'IBM',
        courseType: 'Professional Certificate',
        averageRating: 4.5,
        reviewCount: 15000,
        price: 4067,
        isFree: false,
        level: 'Beginner',
        enrollmentCount: 420000,
        courseraUrl: 'https://www.coursera.org/professional-certificates/ibm-cybersecurity-analyst',
        skills: ['Cybersecurity', 'Network Security', 'Security Analysis', 'SIEM'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=250&fit=crop'
    },
    {
        id: 'paid-7',
        title: 'Meta Front-End Developer Professional Certificate',
        slug: 'meta-frontend-developer',
        description: 'Launch your career as a front-end developer. Learn HTML, CSS, JavaScript, React.',
        provider: 'Meta',
        courseType: 'Professional Certificate',
        averageRating: 4.7,
        reviewCount: 28000,
        price: 4067,
        isFree: false,
        level: 'Beginner',
        enrollmentCount: 750000,
        courseraUrl: 'https://www.coursera.org/professional-certificates/meta-front-end-developer',
        skills: ['HTML', 'CSS', 'JavaScript', 'React', 'UI/UX Design', 'Version Control'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=400&h=250&fit=crop'
    },
    {
        id: 'paid-8',
        title: 'IBM Machine Learning Professional Certificate',
        slug: 'ibm-machine-learning',
        description: 'Master machine learning with Python. Learn supervised, unsupervised, and deep learning.',
        provider: 'IBM',
        courseType: 'Professional Certificate',
        averageRating: 4.7,
        reviewCount: 18000,
        price: 4067,
        isFree: false,
        level: 'Intermediate',
        enrollmentCount: 380000,
        courseraUrl: 'https://www.coursera.org/professional-certificates/ibm-machine-learning',
        skills: ['Machine Learning', 'Python', 'TensorFlow', 'Deep Learning', 'NLP'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400&h=250&fit=crop'
    },
    {
        id: 'paid-9',
        title: 'DeepLearning.AI TensorFlow Developer Professional Certificate',
        slug: 'tensorflow-developer',
        description: 'Master TensorFlow and build machine learning models. Prepare for TensorFlow Certificate.',
        provider: 'DeepLearning.AI',
        courseType: 'Professional Certificate',
        averageRating: 4.8,
        reviewCount: 45000,
        price: 4067,
        isFree: false,
        level: 'Intermediate',
        enrollmentCount: 920000,
        courseraUrl: 'https://www.coursera.org/professional-certificates/tensorflow-in-practice',
        skills: ['TensorFlow', 'Deep Learning', 'Neural Networks', 'Python', 'Computer Vision'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=400&h=250&fit=crop'
    },
    {
        id: 'paid-10',
        title: 'Microsoft Power BI Data Analyst Professional Certificate',
        slug: 'microsoft-power-bi',
        description: 'Learn the skills needed to become a Microsoft Power BI data analyst. Prepare for PL-300.',
        provider: 'Microsoft',
        courseType: 'Professional Certificate',
        averageRating: 4.6,
        reviewCount: 22000,
        price: 4067,
        isFree: false,
        level: 'Intermediate',
        enrollmentCount: 680000,
        courseraUrl: 'https://www.coursera.org/professional-certificates/microsoft-power-bi-data-analyst',
        skills: ['Power BI', 'Data Analysis', 'DAX', 'Data Visualization', 'Business Intelligence'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=250&fit=crop'
    },
    {
        id: 'paid-11',
        title: 'AWS Cloud Technical Essentials',
        slug: 'aws-cloud-essentials',
        description: 'Learn fundamental cloud computing concepts and AWS core services.',
        provider: 'Amazon Web Services',
        courseType: 'Course',
        averageRating: 4.7,
        reviewCount: 35000,
        price: 2407,
        isFree: false,
        level: 'Beginner',
        enrollmentCount: 890000,
        courseraUrl: 'https://www.coursera.org/learn/aws-cloud-technical-essentials',
        skills: ['AWS', 'Cloud Computing', 'EC2', 'S3', 'Cloud Architecture'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=250&fit=crop'
    },
    {
        id: 'paid-12',
        title: 'IBM Full Stack Software Developer Professional Certificate',
        slug: 'ibm-full-stack',
        description: 'Learn to create applications using front-end and back-end technologies.',
        provider: 'IBM',
        courseType: 'Professional Certificate',
        averageRating: 4.6,
        reviewCount: 32000,
        price: 4067,
        isFree: false,
        level: 'Intermediate',
        enrollmentCount: 580000,
        courseraUrl: 'https://www.coursera.org/professional-certificates/ibm-full-stack-cloud-developer',
        skills: ['Python', 'Django', 'Cloud Computing', 'Containers', 'Kubernetes', 'SQL'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400&h=250&fit=crop'
    },
    {
        id: 'paid-13',
        title: 'IBM Generative AI Engineering Professional Certificate',
        slug: 'ibm-generative-ai',
        description: 'Learn to build and deploy generative AI solutions using LLMs and prompt engineering.',
        provider: 'IBM',
        courseType: 'Professional Certificate',
        averageRating: 4.6,
        reviewCount: 3500,
        price: 4897,
        isFree: false,
        level: 'Advanced',
        enrollmentCount: 120000,
        courseraUrl: 'https://www.coursera.org/professional-certificates/ibm-generative-ai-engineering',
        skills: ['Generative AI', 'LLMs', 'Prompt Engineering', 'LangChain', 'AI Agents'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=400&h=250&fit=crop'
    },
    {
        id: 'paid-14',
        title: 'Digital Marketing Professional Certificate',
        slug: 'digital-marketing',
        description: 'Learn digital marketing strategies, SEO, SEM, social media marketing, and analytics.',
        provider: 'Digital Marketing Institute',
        courseType: 'Professional Certificate',
        averageRating: 4.5,
        reviewCount: 12000,
        price: 6557,
        isFree: false,
        level: 'Beginner',
        enrollmentCount: 320000,
        courseraUrl: 'https://www.coursera.org/professional-certificates/digital-marketing-institute',
        skills: ['Digital Marketing', 'SEO', 'SEM', 'Social Media Marketing', 'Analytics'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?w=400&h=250&fit=crop'
    },
    {
        id: 'paid-15',
        title: 'Business Analytics Specialization',
        slug: 'business-analytics',
        description: 'Master business analytics tools and techniques to make data-driven decisions.',
        provider: 'University of Pennsylvania',
        courseType: 'Specialization',
        averageRating: 4.7,
        reviewCount: 42000,
        price: 4067,
        isFree: false,
        level: 'Intermediate',
        enrollmentCount: 890000,
        courseraUrl: 'https://www.coursera.org/specializations/business-analytics',
        skills: ['Business Analytics', 'Data Visualization', 'Excel', 'R Programming', 'Statistics'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=400&h=250&fit=crop'
    },
    {
        id: 'paid-16',
        title: 'Finance Specialization',
        slug: 'finance-spec',
        description: 'Master the fundamentals of finance including corporate finance and investment.',
        provider: 'University of Michigan',
        courseType: 'Specialization',
        averageRating: 4.7,
        reviewCount: 28000,
        price: 49,
        isFree: false,
        level: 'Intermediate',
        enrollmentCount: 680000,
        courseraUrl: 'https://www.coursera.org/specializations/finance-fundamentals',
        skills: ['Finance', 'Corporate Finance', 'Investment Analysis', 'Financial Modeling', 'Valuation'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=400&h=250&fit=crop'
    },
    {
        id: 'paid-17',
        title: 'Python for Everybody Specialization',
        slug: 'python-everybody',
        description: 'Learn to Program and Analyze Data with Python.',
        provider: 'University of Michigan',
        courseType: 'Specialization',
        averageRating: 4.8,
        reviewCount: 330000,
        price: 4067,
        isFree: false,
        level: 'Beginner',
        enrollmentCount: 4500000,
        courseraUrl: 'https://www.coursera.org/specializations/python',
        skills: ['Python', 'Data Structures', 'Database', 'SQL', 'Web Scraping'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=400&h=250&fit=crop'
    },
    {
        id: 'paid-18',
        title: 'Yale Psychology and the Good Life',
        slug: 'psychology-good-life',
        description: 'Learn about psychology and the science of well-being to live a happier life.',
        provider: 'Yale University',
        courseType: 'Course',
        averageRating: 4.9,
        reviewCount: 65000,
        price: 4067,
        isFree: false,
        level: 'All Levels',
        enrollmentCount: 1800000,
        courseraUrl: 'https://www.coursera.org/learn/psychology-the-good-life',
        skills: ['Well-being', 'Positive Psychology', 'Happiness', 'Personal Development'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=250&fit=crop'
    }
];

// Combine all courses
export const mockCourses: Course[] = [...freeCourses, ...freeCertifications, ...paidCourses];

// Helper functions
export const getFreeCourses = () => mockCourses.filter(c => c.price === 0);
export const getPaidCourses = () => mockCourses.filter(c => c.price && c.price > 0);
export const getCoursesByCategory = (category: string) => 
    mockCourses.filter(course => course.category?.slug === category);
export const searchCourses = (query: string) => 
    mockCourses.filter(course => 
        course.title.toLowerCase().includes(query.toLowerCase()) ||
        (course.provider?.toLowerCase().includes(query.toLowerCase()) ?? false) ||
        (course.skills?.some(skill => skill.toLowerCase().includes(query.toLowerCase())) ?? false)
    );
